config/routes.rb
Rails.application.routes.draw do
  resources :tags
  devise_for :admins
  resources :projects
  root 'main#index'
  get 'main/about', to: 'main#about'
  match "*path", to: redirect("/"), via: :all #escondendo todas as rotas indefinidas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	has_and_belongs_to_many :tags

	scope :filter, -> (tag_id) { joins(:tags).where("tags.id = ?", tag_id) }
	# Scope eh uma ferramenta fornecida pelo rails em que podemos criar um metodo
	# (nesse caso filter) para fazermos uma "query".
	# Então se escrevermos Project.filter(3) teremos todos os projetos que possuem
	# uma tag_id = 3, ou seja, o rails selecionara todo os projetos que possuem
	# um relacionamento com a tag de id informado.

	# ATENCAO: notem que utilizo "joins(:tags)" para ter acesso a todas as tags
	# a partir do model de Project.
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_and_belongs_to_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :dont_allow_user_self_registration
  # protect_from_forgery with: :exception

  private
  def after_sign_out_path_for(resource)
    root_path
  end

  private
  # redirecionando rota "admins/sign_up" para o root
  def dont_allow_user_self_registration
    if ['devise/registrations','devise_invitable/registrations'].include?(params[:controller]) && ['new','create'].include?(params[:action])
      redirect_to root_path
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  respond_to :js, :html

  def index
  	@projects = params[:filtered].blank? ? Project.all : Project.filter(params[:filtered])
  	# Sempre que damos "submit" em um formulario html o rails cria um Json(parameters) com os pares
  	# de valores submetidos. No form de filtro (index.html.slim da main) verao que existe
  	# um simbolo :filtered logo a frente de "select_tag". Isso me permite criar arbitrariamente
  	# um novo par nesse Json.(filtered => valor) Assim o rails me permite recuperar esse valor
  	# a partir do comando params[:filtered]. Caso o valor volte branco ele mostrara todos os
  	# projetos, caso contrario, chamara o metodo filter com parametro de params[:filtered].
  	@tags = Tag.all

    respond_to do |format|
      format.js {}
      format.html
    end
  end

  def about
    @text = "what"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_admin!, except: [:show, :index]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.to_a
    unless request['query'].nil?
        query = request['query'].upcase
        @projects.select! { |p| (p.description.upcase.include? query) || (p.name.upcase.include? query) }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Projeto criado com sucesso!' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Projeto editado com sucesso!' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Projeto foi deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :tag_ids => [])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_admin!, except: [:show, :index]
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def log_out_in_helper(current_admin)
    if(current_admin)
      link_to("Sair", destroy_admin_session_path, :method => :delete, class: "btn btn-default")
    else
      link_to("Eu sou administrador", new_admin_session_path, class: "btn btn-default")
    end
  end

  def markdown(text)
  	markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
    	no_intra_emphasis: true, 
    	fenced_code_blocks: true,   
    	disable_indented_code_blocks: false)
		
		return markdown.render(text).html_safe
	end
end

app/helpers/main_helper.rb
module MainHelper

	def text_length(text, size)
		if text.length > size
			"#{text[0, size]}..."
		else
			text
		end
	end

	def get_descriptive_image project
		MainHelper.get_descriptive_image project
	end

	def MainHelper.get_descriptive_image project
		md = project.description
		link = md[/\!\[.*\]\((.*?)\)/]
		(!link.nil?)? link[/\((.*?)\)/][1..-2] : nil
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def link_to_filter(current_admin)
    if(current_admin)
      link_to("Adicionar Projeto", new_project_path, class: "btn btn-default")
      
    end
  end
  
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_messages.html.slim
.messages
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        div class=("alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} msg") role="alert" 
          - if name.to_s == 'notice'
            button.close aria-hidden="true" data-dismiss="alert" type="button"  &times;
            = content_tag :div, msg, :id => "flash_#{name}"
          - else
            button.close aria-hidden="true" data-dismiss="alert" type="button"  &times;
            = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      a.navbar-brand href="/"
        = image_tag 'possibilita-logo.png', class: 'possibilita'
    .navbar-form.navbar-right#nav-items
      ul.nav.navbar-nav.navbar-right
        li
          a href="/"  Início
        li
          a href="/projects"  Projetos
        li
          a href="/main/about"  Sobre
/   = log_out_in_helper(current_admin)

app/views/layouts/_pagefooter.html.slim
.row#footer-up
  .col-md-offset-2.col-md-4
    h6 POSSIBILITA
    = image_tag "footer-line.svg"
    p Uma iniciativa da EMBS / Senses UnB.
  .col-md-offset-2.col-md-3
    h6 REDES SOCIAIS
    = image_tag "footer-line.svg"
    div#footer-icons
      / a href="#"
      /   i.fa.fa-instagram.fa-3x#black-icon.margin-right20 aria-hidden="true"
      a href="https://www.facebook.com/sensesunb"
        i.fa.fa-facebook-square.fa-3x#black-icon.margin-right20 aria-hidden="true"
      / a href="#"
      /   i.fa.fa-slack.fa-3x#black-icon aria-hidden="true"
.row#footer-down
  .col-md-offset-2.col-md-4
    br
    p Possibilita 2017 - Todos os direitos reservados
    br

app/views/layouts/application.html.slim
doctype html
html
  head
    title Possibilita
    link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet"
    link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"
    link href="https://use.fontawesome.com/6d06bdb0ed.css" media="all" rel="stylesheet"
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  body
    == render 'layouts/navbar'
    = yield
    == render 'layouts/pagefooter'

app/views/main/_projects.html.slim
.row#projects_index
  - @projects.take(3).each do |project|
  	.col-sm-6.col-md-4.each_project
      - if !get_descriptive_image(project).nil?
        = image_tag get_descriptive_image(project), alt: "imagem de projeto", class: "project-image"
      h4 = link_to project.name, project, class: "project_title"
      hr
      p = text_length(project.description, 50)

app/views/main/about.html.slim
section.text-center.banner#sobre-nos
    .sobre
        .sobre-texto.col-md-6.col-md-offset-3
            h1.title Sobre nós
            p Acreditamos que todos devem ter acesso ao conhecimento, principalmente se ele pode ajudar alguém a ir mais longe.

.container.sobre-bloco
    .col-md-1.triangle = image_tag "yellow-triangle.svg"
    .col-md-11.titulo-bloco Por quê?
    p.col-md-11.col-md-offset-1 É difícil acreditar que, em um mundo onde a tecnologia permeia a vida de todos, ainda há pessoas que não podem usá-la ao seu favor por falta de acesso. Isso é ainda mais inacreditável quando pensamos em tecnologia assistiva. Como que algo que deveria tornar a vida de todas mais fácil pode ser tão difícil de se alcançar?
.container.sobre-bloco
    .col-md-1.triangle = image_tag "yellow-triangle.svg"
    .col-md-11.titulo-bloco Quem somos?
    p.col-md-11.col-md-offset-1 O Possibilita é um esforço dos estudantes da Universidade de Brasília que participam da EMBS/Senses, uma iniciativa que estuda tecnologia assistiva e qual a melhor forma de desenvolvê-la para a sociedade. Somos estudantes de Engenharia, Design e Computação e queremos mudar o mundo para melhor.
.container.sobre-bloco
    .col-md-1.triangle = image_tag "yellow-triangle.svg"
    .col-md-11.titulo-bloco Como?
    p.col-md-11.col-md-offset-1 Queremos entregar uma plataforma para disponibilizar explicações sobre como fabricar dispositivos que facilitem a interação do ser humano com o seu meio, focando sempre em pessoas com necessidades especiais, sejam elas quais forem. Diante disto, procuramos criar os dispositivos, testá-los sobre todas as condições, pensar em todas as alternativas e, a partir disto, escrever o melhor guia possível, mostrando que tecnologia assistiva não é algo de outro planeta nem uma exclusividade, mas sim algo próximo, distante somente de um passo-a-passo simples para construir uma ferramenta capaz de mudar a vida de muitas pessoas. Esta é a missão do projeto Possibilita.

app/views/main/index.html.slim
section.text-center.banner#main-banner
    .sobre
        .sobre-texto.col-md-6.col-md-offset-3
            h1.title O conhecimento deve estar disponível para todos. A acessibilidade também.
            p Baseados nessa a ideia, o projeto Senses deu início ao Possibilita, uma plataforma de distribuição de projetos de dispositivos de tecnologia assistiva. Todos os projetos deste site foram concebidos com a missão de serem de baixo custo e de fácil acesso a todos aqueles que precisarem.

section#projetos
    .container.projetos-margin
        h3.title projetos
        hr
        == render "projects"
    .col-sm-offset-6.col-md-offset-4.col-sm-6.col-md-4
        = link_to 'Ver mais', "/projects", class: "btn btn-default btn-lg btn-block"

app/views/main/index.js.erb
$("#projects_index").html("<%= j render(partial: 'projects') %>");

app/views/projects/_form.html.slim
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      ul
        - @project.errors.full_messages.each do |message|
          li = message
  .form-horizontal
    .form-group.row
      = f.label :nome
      = f.text_field :name, class: "form-control", required: true
    .form-group.row
      = f.label :descrição
      = f.text_area :description, class: "form-control", required: true
    .form-group.row
      = f.collection_check_boxes :tag_ids, Tag.all, :id, :name
    .actions.form-group.row
      = f.submit 'Salvar Projeto', class: "btn btn-default"

app/views/projects/edit.html.slim
.container  
  h1.form-group.row Editando projeto

  == render 'form'

app/views/projects/index.html.slim
.container
  .row
    .col-md-12.bread
      ol.breadcrumb
        li.breadcrumb-item
          a href="/"
            i.fa.fa-home aria-hidden="true"
        li.breadcrumb-item.active
          = link_to 'projetos', '/projects'
    .col-md-8
      h1 Projetos
    .container.col-md-4
      form
        .form-group.row
          .col-md-10
            input.form-control type="text" name="query" placeholder="Pesquisar"
          .col-md-2
            button.btn.btn-secondary type="submit"
              i.fa.fa-search aria-hidden="true"
- if @projects.length > 0
    - @projects.each do |project|
      .container.sobre-bloco
        .col-md-1.triangle = image_tag "yellow-triangle.svg"
        .col-md-11.titulo-bloco = link_to project.name, project
        .col-md-11.col-md-offset-1
          p = markdown(text_length(project.description, 200))
        = link_to 'Vamos fazer?', project, class: "btn btn-primary pull-right"
        - if current_admin
          = link_to 'Editar', edit_project_path(project), class: "btn btn-primary pull-right"
          = link_to 'Destruir', project, data: { confirm: 'Tem certeza?' }, method: :delete, class: "btn btn-danger pull-right"
- else
  .container.sobre-bloco
    .col-md-1.triangle = image_tag "yellow-triangle.svg"
    .col-md-11.titulo-bloco Nada encontrado!
    .col-md-11.col-md-offset-1
      p Talvez seja hora de procurar outro projeto?

app/views/projects/new.html.slim
.container  
  h1.form-group.row Novo Projeto

  == render 'form'

  = link_to 'Voltar', projects_path

app/views/projects/show.html.slim
.container
  .row
    .col-md-12.bread
      ol.breadcrumb
        li.breadcrumb-item
          a href="/"
            i.fa.fa-home aria-hidden="true"
        li.breadcrumb-item
          = link_to 'projetos', '/projects'
        li.breadcrumb-item.active
          = @project.name
    .col-md-8
      h1.back-button
        a href=projects_path Voltar
    .container.col-md-4
      form
        .form-group.row
          .col-md-10
            input.form-control type="text" id="projectsearch" placeholder="Pesquisar"
          .col-md-2
            button.btn.btn-secondary type="submit"
              i.fa.fa-search aria-hidden="true"
  .container.sobre-bloco
    .col-md-1.triangle = image_tag "yellow-triangle.svg"
    .col-md-11.titulo-bloco = @project.name
    .col-md-11.col-md-offset-1
      .project-description
        = markdown @project.description

app/views/tags/_form.html.slim
= form_for @tag do |f|
  - if @tag.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      ul
        - @tag.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/tags/edit.html.slim
h1 Editing tag

== render 'form'

= link_to 'Show', @tag
'|
= link_to 'Back', tags_path

app/views/tags/index.html.slim
h1 Listing tags

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @tags.each do |tag|
      tr
        td = tag.name
        td = link_to 'Show', tag
        td = link_to 'Edit', edit_tag_path(tag)
        td = link_to 'Destroy', tag, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Tag', new_tag_path

app/views/tags/new.html.slim
h1 New tag

== render 'form'

= link_to 'Back', tags_path

app/views/tags/show.html.slim
p#notice = notice

p
  strong Name:
  = @tag.name

= link_to 'Edit', edit_tag_path(@tag)
'|
= link_to 'Back', tags_path